name: image_gallery_saver_example
description: Demonstrates how to use the image_gallery_saver plugin.
publish_to: none
version: 2.0.3+3

environment:
  sdk: ">=3.3.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^12.0.0+1
  fluttertoast: ^8.2.2
  path_provider: ^2.0.15
  dio: ^5.2.1+1

  image_gallery_saver:
    path: ../
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

