name: image_gallery_saver
description: A flutter plugin for save image to gallery, iOS need to add the following keys to your Info.plist file.
version: 2.0.3
homepage: https://github.com/hui-z/image_gallery_saver

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.lazyarts.vikram.imagegallerysaver
        pluginClass: ImageGallerySaverPlugin
      ios:
        pluginClass: ImageGallerySaverPlugin

dev_dependencies:
  flutter_test:
    sdk: flutter

